### ISSUE TITLE
'Client' object has no attribute 'get_server'

### ISSUE THREAD

**Issue by vinnytroia** [dolphinhats/Discord-Channel-scraper#5]
Hi - i seem to be logging in fine using my toke, but i always get this error. Any ideas?

Logged in as: **
------
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "scrape_channels.py", line 35, in on_ready
    SERVER = client.get_server(SERVER_ID)
AttributeError: 'Client' object has no attribute 'get_server'

**Comment by southbridge-fur** [comment]
This may be due to an update with the library imported for interfacing with the Discord API. Currently I haven't had the time needed to solve this issue. Feel free to figure it out and submit a pull request.

**Comment by empireshades** [comment]
I think this may have been renamed to `get_guild(id)` as per:

[discord.py V1.0 notes](https://github.com/Rapptz/discord.py/blob/f84219c2b2f94133ea1d7989c50547042dc7145e/docs/migrating.rst)

[get_guild in the API docs](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_guild)
